### ISSUE TITLE
downloaded and deployed the loan-approval can't start an instance:  Form failure: Not Found

### ISSUE THREAD

**Issue by Daij-Djan** [camunda/camunda-get-started#2]
Hi,
I downloaded and deployed the loan-approval but everytime I want to start an instance:  Form failure: Not Found

any idea what could be wrong?

server 7.5.0 with tomcat on OS X -- nothing configured, all standard.. as by the tutorial

compare: http://stackoverflow.com/questions/39705594/downloaded-and-deployed-the-tutorial-but-cant-start-instance-form-failure-not

**Comment by meyerdan** [comment]
Hi, please raise this question in the forum (http://forum.camunda.org)
